### PR TITLE
Feature/sc 229 gate sign up behind demo form page

### PR DESCRIPTION
**Pull request by Genoux**
### Gate sign up behind demo form page

We want to filter user from business. So we created a page where we filter companies emails from user emails.

---

**E.g** if a user has _123@gmail.com_ We display "**Thank you for your interest**" _ELSE_ we redirect the user to Hubspot meeting with prefill data.

_I used **VUEJS** for quicker implementation as this is a "single page app" and not fully part of the rest of the site_

**Page at:** _/book-a-demo_

image

### CODE REVIEW

**Comment by afunnydev** [comment]
I think you're missing a lot of stuff in the `book-a-demo` template if you're not putting in the `main` template. I see a lot of stuff in [baseof](https://github.com/inBeat/inbeat-website/blob/master/themes/inbeat/layouts/_default/baseof.html).

Is there another way to do this that would still use our `main`?

**Comment by Genoux** [comment]
> book-a-demo

`book-a-demo` Is kind of his own template. It's more like a middleware, so I don't need most of the stuff used in baseof and main template. - But I'm open for better suggestion! @afunnydev

**Comment by afunnydev** [comment]
I understand. I trust you so please have a look in `baseof` and pick what is needed from there if anything. I believe we at least need the GTM or any trackers?

My problem is that in 6 months, if we are asked to change something in the `head`, we'll need to change it here too and we'll forget 🙃

**Comment by Genoux** [comment]
> I understand. I trust you so please have a look in `baseof` and pick what is needed from there if anything. I believe we at least need the GTM or any trackers?
> 
> My problem is that in 6 months, if we are asked to change something in the `head`, we'll need to change it here too and we'll forget 🙃

Ah yes, make sense! You're right, I can just reuse head/gtm as it's pretty much the same thing I had + Switched from Inter to website main font (neue-haas-unica). 

I did some change - Let me know :)

**Pull request merged**
